/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Customer } from "./types";

// Global Portfolio Stats representing Sanjay Kumar Pandey's complete portfolio
export const GLOBAL_STATS = {
  agentName: "Sanjay Kumar Pandey",
  agentCode: "LU-GPH0020",
  backOffice: "VARANASI CLUSTER",
  regionalOffice: "NORTH CENTRAL RO",
  areaOffice: "GORAKHPUR",
  totalCustomers: 754,
  totalLoans: 1189,
  totalTxnRows: 1693,
  totalDisbursedINR: 969000000, // ₹96.9 Crores
};

export const CUSTOMERS: Customer[] = [
  {
    name: "A P Singh",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "111000013592",
        app_no: "1110015953",
        year: 2019,
        sanction_date: "2019-11-27",
        status: "Stalled / Zero Payout",
        age_days: 2399,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1300000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1300000.0,
        roi: 5.65,
        disbursement_amt: 1300000.0,
        total_disbursed: 0.0,
        pending: 1300000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Improvement / Renovation",
        roi_package: "Online Rewriting (Floating)",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 0,
        has_txn_detail: false,
        any_unrealized: false,
        mandate_status: null,
        collateral_id: null,
        connector_name: null,
        disbursements: []
      }
    ],
    loan_count: 1,
    total_sanctioned: 1300000.0,
    total_disbursed: 0.0,
    total_pending: 1300000.0,
    total_tranches: 0,
    status: "Stalled / Zero Payout"
  },
  {
    name: "Abdul Hai",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "111000016863",
        app_no: "1110020817",
        year: 2021,
        sanction_date: "2021-10-18",
        status: "Fully Disbursed",
        age_days: 1708,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2000000.0,
        roi: 7.76,
        disbursement_amt: 2000000.0,
        total_disbursed: 2000000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Construction Of House",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 6,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "20852870",
        connector_name: null,
        disbursements: [
          {
            date: "2022-01-12",
            disb_type: "FIRST DISB",
            disb_amt: 570000.0,
            canc_amt: 0.0,
            net_disb_amt: 570000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABDUL HAI",
            beneficiary_ac: "10887667403",
            txn_ref: "HDFCR52022011289855069",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20852870"
          },
          {
            date: "2022-01-28",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 700000.0,
            canc_amt: 0.0,
            net_disb_amt: 700000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABDUL HAI",
            beneficiary_ac: "10887667403",
            txn_ref: "HDFCR52022012893169308",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20852870"
          },
          {
            date: "2022-01-31",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 300000.0,
            canc_amt: 0.0,
            net_disb_amt: 300000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABDUL HAI",
            beneficiary_ac: "10887667403",
            txn_ref: "HDFCR52022013193815342",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20852870"
          },
          {
            date: "2022-02-28",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 300000.0,
            canc_amt: 0.0,
            net_disb_amt: 300000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABDUL HAI",
            beneficiary_ac: "10887667403",
            txn_ref: "HDFCR52022022850164610",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20852870"
          },
          {
            date: "2022-03-14",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 80000.0,
            canc_amt: 0.0,
            net_disb_amt: 80000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABDUL HAI",
            beneficiary_ac: "10887667403",
            txn_ref: "N073221873128158",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20852870"
          },
          {
            date: "2022-12-23",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 50000.0,
            canc_amt: 0.0,
            net_disb_amt: 50000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABDUL HAI",
            beneficiary_ac: "10887667403",
            txn_ref: "N357222259538130",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20852870"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 2000000.0,
    total_disbursed: 2000000.0,
    total_pending: 0.0,
    total_tranches: 6,
    status: "Fully Disbursed"
  },
  {
    name: "Abhay Kumar Mishra",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100001383",
        app_no: "1003100001383",
        year: 2023,
        sanction_date: "2023-06-20",
        status: "Fully Disbursed",
        age_days: 1098,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1500000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1500000.0,
        roi: 8.0,
        disbursement_amt: 1500000.0,
        total_disbursed: 1500000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Improvement / Renovation",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 2,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2317000009",
        connector_name: null,
        disbursements: [
          {
            date: "2023-06-27",
            disb_type: "FIRST DISB",
            disb_amt: 1350000.0,
            canc_amt: 0.0,
            net_disb_amt: 1350000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "SHAKUNTALA DEVI",
            beneficiary_ac: "5118101001633",
            txn_ref: "N178232519387409",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2317000009"
          },
          {
            date: "2023-06-30",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 150000.0,
            canc_amt: 0.0,
            net_disb_amt: 150000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "SHAKUNTALA DEVI",
            beneficiary_ac: "5118101001633",
            txn_ref: "N181232524082010",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2317000009"
          }
        ]
      },
      {
        loan_no: "111000018474",
        app_no: "1110023746",
        year: 2022,
        sanction_date: "2022-10-13",
        status: "Fully Disbursed",
        age_days: 1348,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2000000.0,
        roi: 8.75,
        disbursement_amt: 2000000.0,
        total_disbursed: 2000000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "New Griha Vikas(Face Lift)",
        purpose: "Home Entity Loan",
        roi_package: "SCORE LINK FLOATING",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 1,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "21227220",
        connector_name: null,
        disbursements: [
          {
            date: "2022-10-18",
            disb_type: "FIRST DISB",
            disb_amt: 2000000.0,
            canc_amt: 0.0,
            net_disb_amt: 2000000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABHAY KUMAR MISHRA",
            beneficiary_ac: "5626249704",
            txn_ref: "HDFCR52022101853904943",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21227220"
          }
        ]
      },
      {
        loan_no: "111000012975",
        app_no: "1110015630",
        year: 2019,
        sanction_date: "2019-10-11",
        status: "Stalled / Zero Payout",
        age_days: 2446,
        loan_type: "Housing Loan",
        gross_sanction_amt: 700000.0,
        canc_amt: 0.0,
        net_sanction_amt: 700000.0,
        roi: 9.5,
        disbursement_amt: 700000.0,
        total_disbursed: 0.0,
        pending: 700000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash (New Face Lift)",
        purpose: "Home Equity Loan- Repair/Renovation/Extension",
        roi_package: "Online Rewriting (Floating)",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 0,
        has_txn_detail: false,
        any_unrealized: false,
        mandate_status: null,
        collateral_id: null,
        connector_name: null,
        disbursements: []
      },
      {
        loan_no: "111000008269",
        app_no: "1110009861",
        year: 2017,
        sanction_date: "2017-06-21",
        status: "Stalled / Zero Payout",
        age_days: 3288,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1000000.0,
        roi: 9.5,
        disbursement_amt: 1000000.0,
        total_disbursed: 0.0,
        pending: 1000000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Extension Of House / Flat",
        roi_package: "Online Rewriting (Floating)",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 0,
        has_txn_detail: false,
        any_unrealized: false,
        mandate_status: null,
        collateral_id: null,
        connector_name: null,
        disbursements: []
      }
    ],
    loan_count: 4,
    total_sanctioned: 5200000.0,
    total_disbursed: 3500000.0,
    total_pending: 1700000.0,
    total_tranches: 3,
    status: "In Progress / Mixed"
  },
  {
    name: "Abhay Kumar Ojha",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "111000018756",
        app_no: "1110024074",
        year: 2022,
        sanction_date: "2022-12-12",
        status: "Fully Disbursed",
        age_days: 1288,
        loan_type: "Housing Loan",
        gross_sanction_amt: 900000.0,
        canc_amt: 50000.0,
        net_sanction_amt: 850000.0,
        roi: 8.4,
        disbursement_amt: 900000.0,
        total_disbursed: 900000.0,
        pending: -50000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Extension Of House / Flat",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 3,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "21270762",
        connector_name: null,
        disbursements: [
          {
            date: "2022-12-21",
            disb_type: "FIRST DISB",
            disb_amt: 350000.0,
            canc_amt: 0.0,
            net_disb_amt: 350000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABHAY KUMAR OJHA",
            beneficiary_ac: "31140256180",
            txn_ref: "212218168474",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270762"
          },
          {
            date: "2022-12-31",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 300000.0,
            canc_amt: 0.0,
            net_disb_amt: 300000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABHAY KUMAR OJHA",
            beneficiary_ac: "31140256180",
            txn_ref: "212311918055",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270762"
          },
          {
            date: "2023-03-29",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 250000.0,
            canc_amt: 0.0,
            net_disb_amt: 250000.0,
            payment_type: "IFT",
            cheque_no: null,
            beneficiary: "ABHAY KUMAR OJHA",
            beneficiary_ac: "31140256180",
            txn_ref: "303299265152",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270762"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 850000.0,
    total_disbursed: 900000.0,
    total_pending: -50000.0,
    total_tranches: 3,
    status: "Fully Disbursed"
  },
  {
    name: "Abhijeet Ranjan",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100005881",
        app_no: "1003100005881",
        year: 2025,
        sanction_date: "2025-09-09",
        status: "Fully Disbursed",
        age_days: 286,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1700000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1700000.0,
        roi: 7.5,
        disbursement_amt: 1700000.0,
        total_disbursed: 1700000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Improvement / Renovation",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 2,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "20339541",
        connector_name: null,
        disbursements: [
          {
            date: "2025-09-24",
            disb_type: "FIRST DISB",
            disb_amt: 1500000.0,
            canc_amt: 0.0,
            net_disb_amt: 1500000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ABHIJEET RANJAN",
            beneficiary_ac: "2001613177",
            txn_ref: "HDFCN52025092490306746",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20339541"
          },
          {
            date: "2025-09-29",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ABHIJEET RANJAN",
            beneficiary_ac: "2001613177",
            txn_ref: "HDFCN52025092997903187",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20339541"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 1700000.0,
    total_disbursed: 1700000.0,
    total_pending: 0.0,
    total_tranches: 2,
    status: "Fully Disbursed"
  },
  {
    name: "Abhilasha Kumari",
    occupation: "Home Maker",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "111000002179",
        app_no: "1110002690",
        year: 2013,
        sanction_date: "2013-07-25",
        status: "Stalled / Zero Payout",
        age_days: 4715,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1000000.0,
        roi: 14.05,
        disbursement_amt: 950000.0,
        total_disbursed: 0.0,
        pending: 1000000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Construction Of House",
        roi_package: "NEW BHAGYALAKSHMI (LIMITED PERIOD)",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 0,
        has_txn_detail: false,
        any_unrealized: false,
        mandate_status: null,
        collateral_id: null,
        connector_name: null,
        disbursements: []
      }
    ],
    loan_count: 1,
    total_sanctioned: 1000000.0,
    total_disbursed: 0.0,
    total_pending: 1000000.0,
    total_tranches: 0,
    status: "Stalled / Zero Payout"
  },
  {
    name: "Abhishek Singh",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100006221",
        app_no: "1003100006221",
        year: 2026,
        sanction_date: "2026-02-04",
        status: "Fully Disbursed",
        age_days: 138,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2000000.0,
        roi: 7.25,
        disbursement_amt: 2000000.0,
        total_disbursed: 2000000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Improvement / Renovation",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 2,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "21322671",
        connector_name: null,
        disbursements: [
          {
            date: "2026-02-07",
            disb_type: "FIRST DISB",
            disb_amt: 1800000.0,
            canc_amt: 0.0,
            net_disb_amt: 1800000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ABHISHEK SINGH",
            beneficiary_ac: "3693693693693999",
            txn_ref: "HDFCH00790684317",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21322671"
          },
          {
            date: "2026-02-17",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ABHISHEK SINGH",
            beneficiary_ac: "3693693693693999",
            txn_ref: "HDFCH00810789173",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21322671"
          }
        ]
      },
      {
        loan_no: "111000019144",
        app_no: "1110024407",
        year: 2023,
        sanction_date: "2023-02-08",
        status: "Partially Disbursed",
        age_days: 1230,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2850000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2850000.0,
        roi: 8.75,
        disbursement_amt: 2450000.0,
        total_disbursed: 2450000.0,
        pending: 400000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Construction Of House",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 5,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "21322671",
        connector_name: null,
        disbursements: [
          {
            date: "2023-02-28",
            disb_type: "FIRST DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "ABHISHEK SINGH",
            beneficiary_ac: "6773522366",
            txn_ref: "N059232348076706",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21322671"
          },
          {
            date: "2023-03-27",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 300000.0,
            canc_amt: 0.0,
            net_disb_amt: 300000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ABHISHEK SINGH",
            beneficiary_ac: "6773522366",
            txn_ref: "N086232388000478",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21322671"
          },
          {
            date: "2023-03-29",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 400000.0,
            canc_amt: 0.0,
            net_disb_amt: 400000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ABHISHEK SINGH",
            beneficiary_ac: "6773522366",
            txn_ref: "N088232391667565",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21322671"
          },
          {
            date: "2023-03-30",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 800000.0,
            canc_amt: 0.0,
            net_disb_amt: 800000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ABHISHEK SINGH",
            beneficiary_ac: "6773522366",
            txn_ref: "N089232393637043",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21322671"
          },
          {
            date: "2023-09-19",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 750000.0,
            canc_amt: 0.0,
            net_disb_amt: 750000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ABHISHEK SINGH",
            beneficiary_ac: "6773522366",
            txn_ref: "N262232648625999",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21322671"
          }
        ]
      }
    ],
    loan_count: 2,
    total_sanctioned: 4850000.0,
    total_disbursed: 4450000.0,
    total_pending: 400000.0,
    total_tranches: 7,
    status: "In Progress / Mixed"
  },
  {
    name: "Adarsh Chandra Mishra",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100002860",
        app_no: "1003100002860",
        year: 2024,
        sanction_date: "2024-04-12",
        status: "Fully Disbursed",
        age_days: 801,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2200000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2200000.0,
        roi: 8.5,
        disbursement_amt: 2200000.0,
        total_disbursed: 2200000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Construction Of House",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 9,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2409700337",
        connector_name: null,
        disbursements: [
          {
            date: "2024-04-30",
            disb_type: "FIRST DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ADARSH CHANDRA MISHRA",
            beneficiary_ac: "40813439297",
            txn_ref: "N121243011635325",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2409700337"
          },
          {
            date: "2024-05-15",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 350000.0,
            canc_amt: 0.0,
            net_disb_amt: 350000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ADARSH CHANDRA MISHRA",
            beneficiary_ac: "40813439297",
            txn_ref: "N136243041357509",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2409700337"
          },
          {
            date: "2024-05-24",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 100000.0,
            canc_amt: 0.0,
            net_disb_amt: 100000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ADARSH CHANDRA MISHRA",
            beneficiary_ac: "40813439297",
            txn_ref: "N145243055079560",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2409700337"
          },
          {
            date: "2024-05-31",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 350000.0,
            canc_amt: 0.0,
            net_disb_amt: 350000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ADARSH CHANDRA MISHRA",
            beneficiary_ac: "40813439297",
            txn_ref: "N152243065353760",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2409700337"
          },
          {
            date: "2024-06-15",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 250000.0,
            canc_amt: 0.0,
            net_disb_amt: 250000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ADARSH CHANDRA MISHRA",
            beneficiary_ac: "40813439297",
            txn_ref: "N167243098169234",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2409700337"
          },
          {
            date: "2024-06-25",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 350000.0,
            canc_amt: 0.0,
            net_disb_amt: 350000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ADARSH CHANDRA MISHRA",
            beneficiary_ac: "40813439297",
            txn_ref: "N177243111523087",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2409700337"
          },
          {
            date: "2024-06-30",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 300000.0,
            canc_amt: 0.0,
            net_disb_amt: 300000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ADARSH CHANDRA MISHRA",
            beneficiary_ac: "40813439297",
            txn_ref: "N182243120892234",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2409700337"
          },
          {
            date: "2024-09-07",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ADARSH CHANDRA MISHRA",
            beneficiary_ac: "40813439297",
            txn_ref: "N251243254290195",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2409700337"
          },
          {
            date: "2024-09-19",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 100000.0,
            canc_amt: 0.0,
            net_disb_amt: 100000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ADARSH CHANDRA MISHRA",
            beneficiary_ac: "40813439297",
            txn_ref: "N263243276917015",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2409700337"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 2200000.0,
    total_disbursed: 2200000.0,
    total_pending: 0.0,
    total_tranches: 9,
    status: "Fully Disbursed"
  },
  {
    name: "Akshaya Lal",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "111000013254",
        app_no: "1110015937",
        year: 2019,
        sanction_date: "2019-11-22",
        status: "Partially Disbursed",
        age_days: 2404,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2100000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2100000.0,
        roi: 6.6,
        disbursement_amt: 2100000.0,
        total_disbursed: 350000.0,
        pending: 1750000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Extension Of House / Flat",
        roi_package: "Online Rewriting (Floating)",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 2,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "20110865",
        connector_name: null,
        disbursements: [
          {
            date: "2020-06-15",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 250000.0,
            canc_amt: 0.0,
            net_disb_amt: 250000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "AKSHAYA LAL",
            beneficiary_ac: "33727884966",
            txn_ref: "HDFCR52020061583843318",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20110865"
          },
          {
            date: "2020-09-22",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 100000.0,
            canc_amt: 0.0,
            net_disb_amt: 100000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "AKSHAYA LAL",
            beneficiary_ac: "33727884966",
            txn_ref: "N266201251835144",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20110865"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 2100000.0,
    total_disbursed: 350000.0,
    total_pending: 1750000.0,
    total_tranches: 2,
    status: "In Progress / Mixed"
  },
  {
    name: "Alok Kumar Yadav",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100006042",
        app_no: "1003100006042",
        year: 2025,
        sanction_date: "2025-12-11",
        status: "Partially Disbursed",
        age_days: 193,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2150000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2150000.0,
        roi: 7.95,
        disbursement_amt: 1550000.0,
        total_disbursed: 1550000.0,
        pending: 600000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Construction Of House",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 5,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2528000194",
        connector_name: null,
        disbursements: [
          {
            date: "2025-12-20",
            disb_type: "FIRST DISB",
            disb_amt: 50000.0,
            canc_amt: 0.0,
            net_disb_amt: 50000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ALOK KUMAR YADAVA",
            beneficiary_ac: "30245243362",
            txn_ref: "HDFCH00686178660",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2528000194"
          },
          {
            date: "2025-12-24",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 400000.0,
            canc_amt: 0.0,
            net_disb_amt: 400000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ALOK KUMAR YADAV",
            beneficiary_ac: "30245243362",
            txn_ref: "HDFCH00693211491",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2528000194"
          },
          {
            date: "2026-01-15",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 300000.0,
            canc_amt: 0.0,
            net_disb_amt: 300000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ALOK KUMAR YADAV",
            beneficiary_ac: "30245243362",
            txn_ref: "HDFCH00743048718",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2528000194"
          },
          {
            date: "2026-01-31",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 500000.0,
            canc_amt: 0.0,
            net_disb_amt: 500000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ALOK KUMAR YADAV",
            beneficiary_ac: "30245243362",
            txn_ref: "HDFCH00770801170",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2528000194"
          },
          {
            date: "2026-03-13",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 300000.0,
            canc_amt: 0.0,
            net_disb_amt: 300000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ALOK KUMAR YADAV",
            beneficiary_ac: "30245243362",
            txn_ref: "HDFCH00866431487",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2528000194"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 2150000.0,
    total_disbursed: 1550000.0,
    total_pending: 600000.0,
    total_tranches: 5,
    status: "In Progress / Mixed"
  },
  {
    name: "Ambika Prasad Pathak",
    occupation: "Home Maker",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100003240",
        app_no: "1003100003240",
        year: 2024,
        sanction_date: "2024-06-06",
        status: "Fully Disbursed",
        age_days: 746,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2500000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2500000.0,
        roi: 8.5,
        disbursement_amt: 2500000.0,
        total_disbursed: 2500000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Extension Of House / Flat",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 3,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2415800066",
        connector_name: null,
        disbursements: [
          {
            date: "2024-06-20",
            disb_type: "FIRST DISB",
            disb_amt: 1200000.0,
            canc_amt: 0.0,
            net_disb_amt: 1200000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "SAJJAN PATHAK",
            beneficiary_ac: "3629670266",
            txn_ref: "N172243104687696",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2415800066"
          },
          {
            date: "2024-09-23",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 700000.0,
            canc_amt: 0.0,
            net_disb_amt: 700000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "AMBIKA PRASAD PATHAK",
            beneficiary_ac: "1578000100216762",
            txn_ref: "N267243282445380",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2415800066"
          },
          {
            date: "2024-11-19",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 600000.0,
            canc_amt: 0.0,
            net_disb_amt: 600000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "AMBIKA PRASAD PATHAK",
            beneficiary_ac: "1578000100216762",
            txn_ref: "N324243406543319",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2415800066"
          }
        ]
      },
      {
        loan_no: "111000014051",
        app_no: "1110017143",
        year: 2020,
        sanction_date: "2020-08-07",
        status: "Fully Disbursed",
        age_days: 2145,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1000000.0,
        roi: 6.9,
        disbursement_amt: 1000000.0,
        total_disbursed: 1000000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Extension Of House / Flat",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 2,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "20283549",
        connector_name: null,
        disbursements: [
          {
            date: "2020-08-21",
            disb_type: "FIRST DISB",
            disb_amt: 800000.0,
            canc_amt: 0.0,
            net_disb_amt: 800000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "SAJJAN PATHAK",
            beneficiary_ac: "3629670266",
            txn_ref: "HDFCR52020082193725133",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20283549"
          },
          {
            date: "2020-09-07",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "SAJJAN PATHAK",
            beneficiary_ac: "3629670266",
            txn_ref: "N251201236795471",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20283549"
          }
        ]
      },
      {
        loan_no: "111000012449",
        app_no: "1110014562",
        year: 2019,
        sanction_date: "2019-05-27",
        status: "Stalled / Zero Payout",
        age_days: 2583,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1450000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1450000.0,
        roi: 7.25,
        disbursement_amt: 1450000.0,
        total_disbursed: 0.0,
        pending: 1450000.0,
        agent_type: "HLA",
        scheme: "Apna Ghar (M.I.G-I)",
        purpose: "Construction Of House",
        roi_package: "Online Rewriting (Floating)",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 0,
        has_txn_detail: false,
        any_unrealized: false,
        mandate_status: null,
        collateral_id: null,
        connector_name: null,
        disbursements: []
      }
    ],
    loan_count: 3,
    total_sanctioned: 4950000.0,
    total_disbursed: 3500000.0,
    total_pending: 1450000.0,
    total_tranches: 5,
    status: "In Progress / Mixed"
  },
  {
    name: "Akhilesh Kumar Srivastava",
    occupation: "Professional",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100007314",
        app_no: "1003100007314",
        year: 2026,
        sanction_date: "2026-04-20",
        status: "Fully Disbursed",
        age_days: 63,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1000000.0,
        roi: 8.5,
        disbursement_amt: 1000000.0,
        total_disbursed: 1000000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash (New Face Lift)",
        purpose: "Home Equity Loan- Repair/Renovation/Extension",
        roi_package: "SCORE LINK FLOATING NFL",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 2,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "21270479",
        connector_name: null,
        disbursements: [
          {
            date: "2026-04-28",
            disb_type: "FIRST DISB",
            disb_amt: 850000.0,
            canc_amt: 0.0,
            net_disb_amt: 850000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "AKHILESH KUMAR SRIVASTAVA",
            beneficiary_ac: "33028930123",
            txn_ref: "HDFCH00959551300",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270479"
          },
          {
            date: "2026-06-10",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 150000.0,
            canc_amt: 0.0,
            net_disb_amt: 150000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "AKHILESH KUMAR SRIVASTAVA",
            beneficiary_ac: "33028930123",
            txn_ref: "HDFCH01055643294",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270479"
          }
        ]
      },
      {
        loan_no: "111000018841",
        app_no: "1110024056",
        year: 2022,
        sanction_date: "2022-12-08",
        status: "Fully Disbursed",
        age_days: 1292,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1200000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1200000.0,
        roi: 7.65,
        disbursement_amt: 1187256.0,
        total_disbursed: 1198056.0,
        pending: 1944.0,
        agent_type: "HLA",
        scheme: "Griha Suvidha",
        purpose: "Construction Of House",
        roi_package: "Floating",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 7,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "21270479",
        connector_name: null,
        disbursements: [
          {
            date: "2022-12-31",
            disb_type: "FIRST DISB",
            disb_amt: 210800.0,
            canc_amt: 0.0,
            net_disb_amt: 210800.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "MR AKHILESH KUMAR SRIVASTAVA",
            beneficiary_ac: "33028930123",
            txn_ref: "N365222269636422",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270479"
          },
          {
            date: "2023-01-13",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "MR AKHILESH KUMAR SRIVASTAVA",
            beneficiary_ac: "33028930123",
            txn_ref: "N013232290505323",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270479"
          },
          {
            date: "2023-01-24",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "MR AKHILESH KUMAR SRIVASTAVA",
            beneficiary_ac: "33028930123",
            txn_ref: "N024232302177274",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270479"
          },
          {
            date: "2023-01-31",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "MR AKHILESH KUMAR SRIVASTAVA",
            beneficiary_ac: "33028930123",
            txn_ref: "N031232309350596",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270479"
          },
          {
            date: "2023-02-14",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "MR AKHILESH KUMAR SRIVASTAVA",
            beneficiary_ac: "33028930123",
            txn_ref: "N045232332380809",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270479"
          },
          {
            date: "2023-03-30",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 100000.0,
            canc_amt: 0.0,
            net_disb_amt: 100000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "MR AKHILESH KUMAR SRIVASTAVA",
            beneficiary_ac: "33028930123",
            txn_ref: "N089232393646948",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270479"
          },
          {
            date: "2023-05-19",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 87256.0,
            canc_amt: 0.0,
            net_disb_amt: 87256.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "MR AKHILESH KUMAR SRIVASTAVA",
            beneficiary_ac: "33028930123",
            txn_ref: "N139232466685339",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21270479"
          }
        ]
      }
    ],
    loan_count: 2,
    total_sanctioned: 2200000.0,
    total_disbursed: 2198056.0,
    total_pending: 1944.0,
    total_tranches: 9,
    status: "Fully Disbursed"
  },
  {
    name: "Yogendra Prasad",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100005963",
        app_no: "1003100005963",
        year: 2025,
        sanction_date: "2025-10-03",
        status: "Fully Disbursed",
        age_days: 262,
        loan_type: "Housing Loan",
        gross_sanction_amt: 7000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 7000000.0,
        roi: 7.7,
        disbursement_amt: 6944818.0,
        total_disbursed: 6944818.0,
        pending: 55182.0,
        agent_type: "HLA",
        scheme: "Griha Bhoomi",
        purpose: "Plot Purchase And House Constn",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 7,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2526300320",
        connector_name: null,
        disbursements: [
          {
            date: "2025-12-05",
            disb_type: "FIRST DISB",
            disb_amt: 2744818.0,
            canc_amt: 0.0,
            net_disb_amt: 2744818.0,
            payment_type: "CHEQUE",
            cheque_no: "385362",
            beneficiary: "PNB HOUSING FINANCE LIMITED",
            beneficiary_ac: null,
            txn_ref: "FT511216545690",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2526300320"
          },
          {
            date: "2025-12-20",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 700000.0,
            canc_amt: 0.0,
            net_disb_amt: 700000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "YOGENDRA PRASAD",
            beneficiary_ac: "30722442561",
            txn_ref: "HDFCH00686178021",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2526300320"
          },
          {
            date: "2025-12-26",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 400000.0,
            canc_amt: 0.0,
            net_disb_amt: 400000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "YOGENDRA PRASAD",
            beneficiary_ac: "30722442561",
            txn_ref: "HDFCH00696060827",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2526300320"
          },
          {
            date: "2025-12-31",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 500000.0,
            canc_amt: 0.0,
            net_disb_amt: 500000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "YOGENDRA PRASAD",
            beneficiary_ac: "30722442561",
            txn_ref: "HDFCH00704008603",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2526300320"
          },
          {
            date: "2026-02-13",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 1400000.0,
            canc_amt: 0.0,
            net_disb_amt: 1400000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "YOGENDRA PRASAD",
            beneficiary_ac: "30722442561",
            txn_ref: "HDFCH00804538607",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2526300320"
          },
          {
            date: "2026-03-31",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 1000000.0,
            canc_amt: 0.0,
            net_disb_amt: 1000000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "YOGENDRA PRASAD",
            beneficiary_ac: "30722442561",
            txn_ref: "HDFCH00899661015",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2526300320"
          },
          {
            date: "2026-04-30",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "YOGENDRA PRASAD",
            beneficiary_ac: "30722442561",
            txn_ref: "HDFCH00965628350",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2526300320"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 7000000.0,
    total_disbursed: 6944818.0,
    total_pending: 55182.0,
    total_tranches: 7,
    status: "Fully Disbursed"
  },
  {
    name: "Sarita Singh",
    occupation: "Self Employed",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100006951",
        app_no: "1003100006951",
        year: 2026,
        sanction_date: "2026-03-05",
        status: "Fully Disbursed",
        age_days: 109,
        loan_type: "Housing Loan",
        gross_sanction_amt: 10000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 10000000.0,
        roi: 8.05,
        disbursement_amt: 9858400.0,
        total_disbursed: 10000000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Suvidha Asha Banking Surrogate",
        purpose: "Extension Of House / Flat",
        roi_package: "FLOATING GRIHA SUVIDHA ASHA BANKING SURROGATE",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 3,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2605100193",
        connector_name: null,
        disbursements: [
          {
            date: "2026-03-19",
            disb_type: "FIRST DISB",
            disb_amt: 9000000.0,
            canc_amt: 0.0,
            net_disb_amt: 9000000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "NARENDRA PRATAP SINGH",
            beneficiary_ac: "157570822893",
            txn_ref: "HDFCH00876545013",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2605100193"
          },
          {
            date: "2026-03-31",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 100000.0,
            canc_amt: 0.0,
            net_disb_amt: 100000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "NARENDRA PRATAP SINGH",
            beneficiary_ac: "157570822893",
            txn_ref: "HDFCH00899664014",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2605100193"
          },
          {
            date: "2026-04-08",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 900000.0,
            canc_amt: 0.0,
            net_disb_amt: 900000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "NARENDRA PRATAP SINGH",
            beneficiary_ac: "157570822893",
            txn_ref: "HDFCH00922375595",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2605100193"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 10000000.0,
    total_disbursed: 10000000.0,
    total_pending: 0.0,
    total_tranches: 3,
    status: "Fully Disbursed"
  },
  {
    name: "Manoj Kumar Pandey",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100006670",
        app_no: "1003100006670",
        year: 2026,
        sanction_date: "2026-01-09",
        status: "Partially Disbursed",
        age_days: 164,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2950000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2950000.0,
        roi: 7.65,
        disbursement_amt: 1550000.0,
        total_disbursed: 1550000.0,
        pending: 1400000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Construction Of House",
        roi_package: "NTC-FLOATING",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 3,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2609900115",
        connector_name: null,
        disbursements: [
          {
            date: "2026-03-07",
            disb_type: "FIRST DISB",
            disb_amt: 10000.0,
            canc_amt: 0.0,
            net_disb_amt: 10000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "MANOJ KUMAR PANDEY",
            beneficiary_ac: "12080100023468",
            txn_ref: "HDFCH00852553015",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2609900115"
          },
          {
            date: "2026-04-08",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 1200000.0,
            canc_amt: 0.0,
            net_disb_amt: 1200000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "MANOJ KUMAR PANDEY",
            beneficiary_ac: "12080100023468",
            txn_ref: "HDFCH00922370271",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2609900115"
          },
          {
            date: "2026-06-06",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 340000.0,
            canc_amt: 0.0,
            net_disb_amt: 340000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "MANOJ KUMAR PANDEY",
            beneficiary_ac: "12080100023468",
            txn_ref: "HDFCH01045831823",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2609900115"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 2950000.0,
    total_disbursed: 1550000.0,
    total_pending: 1400000.0,
    total_tranches: 3,
    status: "In Progress / Mixed"
  },
  {
    name: "Yogita Singh",
    occupation: "Home Maker",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "111000018895",
        app_no: "1110024276",
        year: 2022,
        sanction_date: "2022-12-30",
        status: "Fully Disbursed",
        age_days: 1270,
        loan_type: "Housing Loan",
        gross_sanction_amt: 2000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 2000000.0,
        roi: 9.35,
        disbursement_amt: 2000000.0,
        total_disbursed: 2000000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash (New Face Lift)",
        purpose: "Home Equity Loan- Repair/Renovation/Extension",
        roi_package: "SCORE LINK FLOATING",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 1,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "21297284",
        connector_name: null,
        disbursements: [
          {
            date: "2023-01-13",
            disb_type: "FIRST DISB",
            disb_amt: 2000000.0,
            canc_amt: 0.0,
            net_disb_amt: 2000000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "RAMDYAL SINGH",
            beneficiary_ac: "31450619540",
            txn_ref: "HDFCR52023011375316547",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21297284"
          }
        ]
      },
      {
        loan_no: "111000017122",
        app_no: "1110021899",
        year: 2022,
        sanction_date: "2022-02-15",
        status: "Fully Disbursed",
        age_days: 1588,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1000000.0,
        roi: 9.35,
        disbursement_amt: 1000000.0,
        total_disbursed: 1000000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash (New Face Lift)",
        purpose: "Home Equity Loan- Repair/Renovation/Extension",
        roi_package: "SCORE LINK FLOATING",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 1,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "20988280",
        connector_name: null,
        disbursements: [
          {
            date: "2022-02-21",
            disb_type: "FIRST DISB",
            disb_amt: 1000000.0,
            canc_amt: 0.0,
            net_disb_amt: 1000000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "RAMDYAL SINGH",
            beneficiary_ac: "31450619540",
            txn_ref: "HDFCR52022022198412942",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20988280"
          }
        ]
      },
      {
        loan_no: "111000015158",
        app_no: "1110018829",
        year: 2021,
        sanction_date: "2021-02-02",
        status: "Fully Disbursed",
        age_days: 1966,
        loan_type: "Housing Loan",
        gross_sanction_amt: 900000.0,
        canc_amt: 0.0,
        net_sanction_amt: 900000.0,
        roi: 6.9,
        disbursement_amt: 900000.0,
        total_disbursed: 900000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Improvement / Renovation",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 2,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "20499571",
        connector_name: null,
        disbursements: [
          {
            date: "2021-02-16",
            disb_type: "FIRST DISB",
            disb_amt: 700000.0,
            canc_amt: 0.0,
            net_disb_amt: 700000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "RAM DAYAL SINGH",
            beneficiary_ac: "31450619540",
            txn_ref: "HDFCR52021021676118723",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20499571"
          },
          {
            date: "2021-02-20",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 200000.0,
            canc_amt: 0.0,
            net_disb_amt: 200000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "RAM DAYAL SINGH",
            beneficiary_ac: "31450619540",
            txn_ref: "N051211413492744",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "20499571"
          }
        ]
      }
    ],
    loan_count: 3,
    total_sanctioned: 3900000.0,
    total_disbursed: 3900000.0,
    total_pending: 0.0,
    total_tranches: 5,
    status: "Fully Disbursed"
  },
  {
    name: "Kaushal Kumar Singh",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "111000018244",
        app_no: "1110023376",
        year: 2022,
        sanction_date: "2022-08-20",
        status: "Fully Disbursed",
        age_days: 1402,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1500000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1500000.0,
        roi: 7.5,
        disbursement_amt: 1500000.0,
        total_disbursed: 1500000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Improvement / Renovation",
        roi_package: "FREEDOM@75",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 1,
        has_txn_detail: true,
        any_unrealized: true,
        mandate_status: "APPROVED",
        collateral_id: "21179401",
        connector_name: null,
        disbursements: [
          {
            date: "2022-08-31",
            disb_type: "FIRST DISB",
            disb_amt: 1500000.0,
            canc_amt: 0.0,
            net_disb_amt: 1500000.0,
            payment_type: "RTGS",
            cheque_no: null,
            beneficiary: "KAUSHAL KUMAR SINGH",
            beneficiary_ac: "718210110001155",
            txn_ref: "HDFCR52022083192647319",
            realization: "PAYMENT UN-REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "21179401"
          }
        ]
      },
      {
        loan_no: "111000008195",
        app_no: "1110009824",
        year: 2017,
        sanction_date: "2017-06-17",
        status: "Stalled / Zero Payout",
        age_days: 3292,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1000000.0,
        roi: 11.8,
        disbursement_amt: 1000000.0,
        total_disbursed: 0.0,
        pending: 1000000.0,
        agent_type: "HLA",
        scheme: "Griha Vikas",
        purpose: "Home Entity Loan",
        roi_package: "FLOATING NON-CORE",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 0,
        has_txn_detail: false,
        any_unrealized: false,
        mandate_status: null,
        collateral_id: null,
        connector_name: null,
        disbursements: []
      }
    ],
    loan_count: 2,
    total_sanctioned: 2500000.0,
    total_disbursed: 1500000.0,
    total_pending: 1000000.0,
    total_tranches: 1,
    status: "In Progress / Mixed"
  },
  {
    name: "Kush Maurya",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAR PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100004008",
        app_no: "1003100004008",
        year: 2024,
        sanction_date: "2024-10-25",
        status: "Fully Disbursed",
        age_days: 605,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1350000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1350000.0,
        roi: 8.5,
        disbursement_amt: 1300000.0,
        total_disbursed: 1300000.0,
        pending: 50000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Extension Of House / Flat",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 2,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2429500181",
        connector_name: null,
        disbursements: [
          {
            date: "2024-11-28",
            disb_type: "FIRST DISB",
            disb_amt: 1200000.0,
            canc_amt: 0.0,
            net_disb_amt: 1200000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "KUSH MAURYA",
            beneficiary_ac: "50161038392",
            txn_ref: "N333243420762532",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2429500181"
          },
          {
            date: "2025-03-28",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 100000.0,
            canc_amt: 0.0,
            net_disb_amt: 100000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "KUSH MAURYA",
            beneficiary_ac: "50161038392",
            txn_ref: "HDFCN52025032842329276",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2429500181"
          }
        ]
      },
      {
        loan_no: "1003100003827",
        app_no: "1003100003827",
        year: 2024,
        sanction_date: "2024-09-26",
        status: "Fully Disbursed",
        age_days: 634,
        loan_type: "Housing Loan",
        gross_sanction_amt: 750000.0,
        canc_amt: 0.0,
        net_sanction_amt: 750000.0,
        roi: 9.75,
        disbursement_amt: 750000.0,
        total_disbursed: 750000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Vikas",
        purpose: "Home Entity Loan",
        roi_package: "SCORE LINK FLOATING",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 1,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2426900145",
        connector_name: null,
        disbursements: [
          {
            date: "2024-10-19",
            disb_type: "FIRST DISB",
            disb_amt: 750000.0,
            canc_amt: 0.0,
            net_disb_amt: 750000.0,
            payment_type: "CHEQUE",
            cheque_no: "197251",
            beneficiary: "KUSH MAURYA LOAN ACCOUNT NO UCL024301943627 YES BANK",
            beneficiary_ac: null,
            txn_ref: "FT410148753047",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2426900145"
          }
        ]
      },
      {
        loan_no: "1003100003246",
        app_no: "1003100003246",
        year: 2024,
        sanction_date: "2024-06-10",
        status: "Partially Disbursed",
        age_days: 742,
        loan_type: "Housing Loan",
        gross_sanction_amt: 1925000.0,
        canc_amt: 0.0,
        net_sanction_amt: 1925000.0,
        roi: 8.5,
        disbursement_amt: 1800000.0,
        total_disbursed: 1800000.0,
        pending: 125000.0,
        agent_type: "HLA",
        scheme: "Griha Prakash",
        purpose: "Extension Of House / Flat",
        roi_package: "GRIHA SIDDHI",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 4,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2415900271",
        connector_name: null,
        disbursements: [
          {
            date: "2024-06-15",
            disb_type: "FIRST DISB",
            disb_amt: 800000.0,
            canc_amt: 0.0,
            net_disb_amt: 800000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "KUSH MAURYA",
            beneficiary_ac: "50161038392",
            txn_ref: "N167243097833094",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2415900271"
          },
          {
            date: "2024-08-14",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 600000.0,
            canc_amt: 0.0,
            net_disb_amt: 600000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "KUSH MAURYA",
            beneficiary_ac: "50161038392",
            txn_ref: "N227243208804800",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2415900271"
          },
          {
            date: "2024-08-31",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 300000.0,
            canc_amt: 0.0,
            net_disb_amt: 300000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "KUSH MAURYA",
            beneficiary_ac: "50161038392",
            txn_ref: "N244243236650928",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2415900271"
          },
          {
            date: "2024-10-11",
            disb_type: "SUBSEQUENT DISB",
            disb_amt: 100000.0,
            canc_amt: 0.0,
            net_disb_amt: 100000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "KUSH MAURYA",
            beneficiary_ac: "50161038392",
            txn_ref: "N285243327966314",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2415900271"
          }
        ]
      }
    ],
    loan_count: 3,
    total_sanctioned: 4025000.0,
    total_disbursed: 3850000.0,
    total_pending: 175000.0,
    total_tranches: 7,
    status: "In Progress / Mixed"
  },
  {
    name: "Anurag Tripathi",
    occupation: "Salaried",
    regional_office: "NORTH CENTRAL RO",
    back_office: "VARANASI CLUSTER",
    area_office: "GORAKHPUR",
    agent_name: "SANJAY KUMAN PANDEY",
    agent_code: "LU-GPH0020",
    loans: [
      {
        loan_no: "1003100004258",
        app_no: "1003100004258",
        year: 2024,
        sanction_date: "2024-12-11",
        status: "Fully Disbursed",
        age_days: 558,
        loan_type: "Housing Loan",
        gross_sanction_amt: 3000000.0,
        canc_amt: 0.0,
        net_sanction_amt: 3000000.0,
        roi: 9.75,
        disbursement_amt: 3000000.0,
        total_disbursed: 3000000.0,
        pending: 0.0,
        agent_type: "HLA",
        scheme: "Griha Vikas",
        purpose: "Home Entity Loan",
        roi_package: "SCORE LINK FLOATING",
        interest_type: "Reducing",
        product_code: "HL",
        tranche_count: 1,
        has_txn_detail: true,
        any_unrealized: false,
        mandate_status: "APPROVED",
        collateral_id: "CT2434500879",
        connector_name: null,
        disbursements: [
          {
            date: "2024-12-30",
            disb_type: "FIRST DISB",
            disb_amt: 3000000.0,
            canc_amt: 0.0,
            net_disb_amt: 3000000.0,
            payment_type: "NEFT",
            cheque_no: null,
            beneficiary: "ANURAG TRIPATHI",
            beneficiary_ac: "25301614926",
            txn_ref: "N365243479818028",
            realization: "PAYMENT REALIZED",
            mandate_status: "APPROVED",
            connector_name: null,
            collateral_id: "CT2434500879"
          }
        ]
      }
    ],
    loan_count: 1,
    total_sanctioned: 3000000.0,
    total_disbursed: 3000000.0,
    total_pending: 0.0,
    total_tranches: 1,
    status: "Fully Disbursed"
  }
];
